# -*- coding: utf-8 -*-
"""indian pines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSQkpK1E8Vb8CYaYKEnKYTOdsnE51740
"""

# === WHT + XGBoost + 3D CNN for Indian Pines (Publication-Ready Version, with Fixes) ===

# === Install Dependencies ===
!pip install xgboost scikit-learn matplotlib seaborn scipy tensorflow pandas --quiet

# === Import Libraries ===
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy.io import loadmat
from scipy.linalg import hadamard
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, cohen_kappa_score, classification_report
from sklearn.cluster import KMeans
from xgboost import XGBClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv3D, Dense, Dropout, Flatten, Input, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from google.colab import files
import os

# === Upload Dataset Files ===
print("\U0001F4C1 Upload: Indian_pines_corrected.mat, Indian_pines_gt.mat")
uploaded = files.upload()

# === Normalize Function ===
def normalize(X):
    X_reshaped = X.reshape(-1, X.shape[-1])
    X_scaled = StandardScaler().fit_transform(X_reshaped)
    return X_scaled.reshape(X.shape)

# === Block Feature Extraction (WHT on Flattened Blocks)
def extract_block_features(data):
    h, w, b = data.shape
    block_size = 8
    H = hadamard(block_size * block_size)
    cs_index, es_index, ts_index = 0, 8, 9
    features = []
    for band in range(b):
        img = data[:, :, band]
        cs = es = ts = 0
        for i in range(0, h - block_size + 1, block_size):
            for j in range(0, w - block_size + 1, block_size):
                block = img[i:i+block_size, j:j+block_size].flatten()
                transformed = np.dot(H, block) / np.sqrt(64)
                cs += transformed[cs_index]**2
                es += transformed[es_index]**2
                ts += transformed[ts_index]**2
        features.append([cs, es, ts])
    return np.array(features)

# === Band Selection: XGBoost + KMeans on WHT Features
def hybrid_band_selection(data, gt, num_bands=20):
    h, w, b = data.shape
    X = data.reshape(-1, b)
    y = gt.flatten()
    mask = y > 0
    X, y = X[mask], y[mask] - 1
    model = XGBClassifier(n_estimators=128, max_depth=10, use_label_encoder=False, eval_metric='logloss')
    model.fit(X, y)
    importances = model.feature_importances_
    top_indices = np.argsort(importances)[::-1][:30]
    feature_vectors = extract_block_features(data)
    top_features = feature_vectors[top_indices]
    scaled = StandardScaler().fit_transform(top_features)
    kmeans = KMeans(n_clusters=num_bands, random_state=42).fit(scaled)
    selected = []
    for c in kmeans.cluster_centers_:
        dist = np.linalg.norm(scaled - c, axis=1)
        selected.append(top_indices[np.argmin(dist)])
    return sorted(selected), feature_vectors

# === Patch Creation
def create_patches(data, labels, band_indices, patch_size=11):
    margin = patch_size // 2
    padded = np.pad(data[:, :, band_indices], ((margin, margin), (margin, margin), (0, 0)), mode='constant')
    X, y, coords = [], [], []
    for i in range(margin, data.shape[0] - margin):
        for j in range(margin, data.shape[1] - margin):
            if labels[i, j] != 0:
                patch = padded[i-margin:i+margin+1, j-margin:j+margin+1, :]
                X.append(patch)
                y.append(labels[i, j] - 1)
                coords.append((i, j))
    return np.array(X), np.array(y), coords

# === 3D CNN Model
def build_cnn(input_shape, num_classes):
    model = Sequential([
        Input(shape=input_shape),
        Conv3D(8, (3, 3, 7), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(16, (3, 3, 5), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(32, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(64, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(128, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Flatten(),
        Dense(256, activation='relu'), Dropout(0.3),
        Dense(128, activation='relu'), Dropout(0.3),
        Dense(64, activation='relu'), Dropout(0.3),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# === Final Pipeline ===
def run_pipeline():
    data = loadmat('Indian_pines_corrected.mat')['indian_pines_corrected']
    gt = loadmat('Indian_pines_gt.mat')['indian_pines_gt']
    print("\n🚀 Running on Indian Pines...")
    data = normalize(data)
    selected_bands, strength_table = hybrid_band_selection(data, gt)
    print(f"\n🎯 Selected Bands: {selected_bands}")

    # Display strength table
    strength_data = []
    for i in selected_bands:
        cs, es, ts = strength_table[i]
        strength_data.append({'Band': int(i), 'Color Strength': cs, 'Edge Strength': es, 'Texture Strength': ts})
    df_strength = pd.DataFrame(strength_data)
    print("\U0001F4CA Feature Strengths per Selected Band:")
    display(df_strength.round(2))

    X, y, coords = create_patches(data, gt, selected_bands)
    y_cat = to_categorical(y)
    X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.4, random_state=42, stratify=y)

    model = build_cnn(X_train[0].shape + (1,), y_cat.shape[1])
    early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    model.fit(X_train[..., np.newaxis], y_train,
              batch_size=256, epochs=50, validation_split=0.3,
              callbacks=[early_stop], verbose=2)

    y_pred = np.argmax(model.predict(X_test[..., np.newaxis]), axis=1)
    y_true = np.argmax(y_test, axis=1)
    acc = accuracy_score(y_true, y_pred)
    kappa = cohen_kappa_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred)
    class_acc = cm.diagonal() / cm.sum(axis=1)
    aa = np.mean(class_acc)

    print("\n📊 Classification Report:")
    report_df = pd.DataFrame(classification_report(y_true, y_pred, output_dict=True)).T
    display(report_df.round(4))

    print(f"\n✅ Final Metrics for Indian Pines:")
    print(f"Overall Accuracy (OA): {acc:.4f}")
    print(f"Kappa Coefficient    : {kappa:.4f}")
    print(f"Average Accuracy (AA): {aa:.4f}")

    # === Confusion Matrix ===
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title("Confusion Matrix - Indian Pines")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

    # === Show GT vs Predicted Map ===
    h, w, _ = data.shape
    pred_map = np.zeros((h, w)) - 1
    X_coords, y_coords = zip(*coords)
    predictions = model.predict(X[..., np.newaxis]).argmax(axis=1)
    for idx, (i, j) in enumerate(coords):
        pred_map[i, j] = predictions[idx]

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(gt, cmap='tab20')
    plt.title("Ground Truth")
    plt.axis('off')
    plt.subplot(1, 2, 2)
    plt.imshow(pred_map, cmap='tab20')
    plt.title("Predicted Map")
    plt.axis('off')
    plt.tight_layout()
    plt.show()

# === Run ===
run_pipeline()