# -*- coding: utf-8 -*-
"""pavia university.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANo5Vk3J_NP2dSye5HUs_VcYm9XZnX0x
"""

# === WHT + XGBoost + 3D CNN for Pavia University (Publication-Ready Version) ===

# === Install Required Libraries ===
!pip install xgboost scikit-learn matplotlib seaborn scipy tensorflow pandas --quiet

# === Import Libraries ===
import numpy as np                                    # Numerical computations
import matplotlib.pyplot as plt                       # Plotting graphs
import seaborn as sns                                 # Better-looking plots
import pandas as pd                                   # Handling tables
from scipy.io import loadmat                          # Loading .mat files (PaviaU datasets)
from scipy.linalg import hadamard                     # Walsh-Hadamard Transform
from sklearn.model_selection import train_test_split  # Splitting data into train/test
from sklearn.preprocessing import StandardScaler      # Normalizing features
from sklearn.metrics import accuracy_score, confusion_matrix, cohen_kappa_score, classification_report
from sklearn.cluster import KMeans                    # Clustering for band selection
from xgboost import XGBClassifier                     # XGBoost classifier
from tensorflow.keras.models import Sequential        # For building deep learning model
from tensorflow.keras.layers import (Conv3D, Dense, Dropout, Flatten, Input, BatchNormalization)
from tensorflow.keras.optimizers import Adam          # Optimizer for CNN
from tensorflow.keras.utils import to_categorical     # Convert labels to one-hot encoding
from tensorflow.keras.callbacks import EarlyStopping  # Stop training if validation gets worse
from google.colab import files                        # Upload files in Google Colab
import os

# === Upload Pavia University Dataset Files ===
print("\U0001F4C1 Upload: PaviaU.mat, PaviaU_gt.mat")
uploaded = files.upload()

# === Function to Normalize Hyperspectral Data ===
def normalize(X):
    # Reshape the data to 2D: (num_pixels, num_bands)
    X_reshaped = X.reshape(-1, X.shape[-1])
    # Standardize each band to mean=0, std=1
    X_scaled = StandardScaler().fit_transform(X_reshaped)
    # Reshape it back to original shape
    return X_scaled.reshape(X.shape)

# === Function to Extract Block Features using Walsh-Hadamard Transform ===
def extract_block_features(data):
    h, w, b = data.shape                 # Get height, width, and number of bands
    block_size = 8                      # Divide image into 8x8 blocks
    H = hadamard(block_size * block_size)  # Create 64x64 Hadamard matrix

    # Indices for color, edge, texture in WHT output
    cs_index, es_index, ts_index = 0, 8, 9
    features = []

    # For every band in the image
    for band in range(b):
        img = data[:, :, band]
        cs = es = ts = 0  # Initialize strengths for current band

        # Divide image into non-overlapping 8x8 blocks
        for i in range(0, h - block_size + 1, block_size):
            for j in range(0, w - block_size + 1, block_size):
                block = img[i:i+block_size, j:j+block_size].flatten()     # Flatten 8x8 to 1D (64,)
                transformed = np.dot(H, block) / np.sqrt(64)              # Apply WHT
                cs += transformed[cs_index]**2
                es += transformed[es_index]**2
                ts += transformed[ts_index]**2

        features.append([cs, es, ts])  # Save all 3 features for this band
    return np.array(features)

# === Band Selection using XGBoost and KMeans on WHT Features ===
def hybrid_band_selection(data, gt, num_bands=20):
    h, w, b = data.shape
    X = data.reshape(-1, b)              # Reshape for classifier
    y = gt.flatten()                     # Flatten ground truth
    mask = y > 0                         # Ignore background (label 0)
    X, y = X[mask], y[mask] - 1          # Filter valid pixels and shift class labels to start from 0

    # Train XGBoost classifier to rank band importance
    model = XGBClassifier(n_estimators=128, max_depth=10, use_label_encoder=False, eval_metric='logloss')
    model.fit(X, y)
    importances = model.feature_importances_

    # Pick top 30 important bands
    top_indices = np.argsort(importances)[::-1][:30]

    # Extract WHT-based block features for those bands
    feature_vectors = extract_block_features(data)
    top_features = feature_vectors[top_indices]

    # Normalize feature vectors and apply KMeans clustering
    scaled = StandardScaler().fit_transform(top_features)
    kmeans = KMeans(n_clusters=num_bands, random_state=42).fit(scaled)

    # Pick closest band from each cluster center
    selected = []
    for c in kmeans.cluster_centers_:
        dist = np.linalg.norm(scaled - c, axis=1)
        selected.append(top_indices[np.argmin(dist)])
    return sorted(selected), feature_vectors

# === Create 3D Patches from Image and Labels ===
def create_patches(data, labels, band_indices, patch_size=11):
    margin = patch_size // 2
    # Pad image to allow patch creation at edges
    padded = np.pad(data[:, :, band_indices], ((margin, margin), (margin, margin), (0, 0)), mode='constant')

    X, y, coords = [], [], []

    # Slide a patch window over the image
    for i in range(margin, data.shape[0] - margin):
        for j in range(margin, data.shape[1] - margin):
            if labels[i, j] != 0:
                patch = padded[i-margin:i+margin+1, j-margin:j+margin+1, :]
                X.append(patch)
                y.append(labels[i, j] - 1)  # Shift class label
                coords.append((i, j))       # Save pixel coordinate
    return np.array(X), np.array(y), coords

# === Build the 3D CNN Model ===
def build_cnn(input_shape, num_classes):
    model = Sequential([
        Input(shape=input_shape),
        Conv3D(8, (3, 3, 7), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(16, (3, 3, 5), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(32, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(64, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Conv3D(128, (3, 3, 3), activation='relu', padding='valid'), BatchNormalization(),
        Flatten(),
        Dense(256, activation='relu'), Dropout(0.3),
        Dense(128, activation='relu'), Dropout(0.3),
        Dense(64, activation='relu'), Dropout(0.3),
        Dense(num_classes, activation='softmax')  # Output layer with softmax for multi-class classification
    ])
    model.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# === Complete Pipeline Execution ===
def run_pipeline():
    # Load data and ground truth
    data = loadmat('PaviaU.mat')['paviaU']
    gt = loadmat('PaviaU_gt.mat')['paviaU_gt']

    print("\n🚀 Running on Pavia University...")

    # Normalize the data cube
    data = normalize(data)

    # Select bands and extract features
    selected_bands, strength_table = hybrid_band_selection(data, gt)
    print(f"\n🎯 Selected Bands: {selected_bands}")

    # Display band-wise WHT feature strengths
    strength_data = []
    for i in selected_bands:
        cs, es, ts = strength_table[i]
        strength_data.append({'Band': int(i), 'Color Strength': cs, 'Edge Strength': es, 'Texture Strength': ts})
    df_strength = pd.DataFrame(strength_data)
    print("\U0001F4CA Feature Strengths per Selected Band:")
    display(df_strength.round(2))

    # Prepare 3D patches
    X, y, coords = create_patches(data, gt, selected_bands)
    y_cat = to_categorical(y)  # One-hot encode labels

    # Split into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.4, random_state=42, stratify=y)

    # Build and train the CNN model
    model = build_cnn(X_train[0].shape + (1,), y_cat.shape[1])
    early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    model.fit(X_train[..., np.newaxis], y_train,
              batch_size=256, epochs=50, validation_split=0.3,
              callbacks=[early_stop], verbose=2)

    # Make predictions on test set
    y_pred = np.argmax(model.predict(X_test[..., np.newaxis]), axis=1)
    y_true = np.argmax(y_test, axis=1)

    # Calculate metrics
    acc = accuracy_score(y_true, y_pred)
    kappa = cohen_kappa_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred)
    class_acc = cm.diagonal() / cm.sum(axis=1)
    aa = np.mean(class_acc)

    # Display classification report
    print("\n📊 Classification Report:")
    report_df = pd.DataFrame(classification_report(y_true, y_pred, output_dict=True)).T
    display(report_df.round(4))

    # Print final evaluation metrics
    print(f"\n✅ Final Metrics for Pavia University:")
    print(f"Overall Accuracy (OA): {acc:.4f}")
    print(f"Kappa Coefficient    : {kappa:.4f}")
    print(f"Average Accuracy (AA): {aa:.4f}")

    # === Confusion Matrix Heatmap ===
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title("Confusion Matrix - Pavia University")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

    # === Visualize Ground Truth vs Predicted Map ===
    h, w, _ = data.shape
    pred_map = np.zeros((h, w)) - 1  # Initialize prediction map
    X_coords, y_coords = zip(*coords)
    predictions = model.predict(X[..., np.newaxis]).argmax(axis=1)

    for idx, (i, j) in enumerate(coords):
        pred_map[i, j] = predictions[idx]

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(gt, cmap='tab20')
    plt.title("Ground Truth")
    plt.axis('off')
    plt.subplot(1, 2, 2)
    plt.imshow(pred_map, cmap='tab20')
    plt.title("Predicted Map")
    plt.axis('off')
    plt.tight_layout()
    plt.show()

# === Run the Full Pipeline ===
run_pipeline()